/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    Users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    Users: User;
    Resources: Resource;
    Messages: Message;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    Users: UsersSelect<false> | UsersSelect<true>;
    Resources: ResourcesSelect<false> | ResourcesSelect<true>;
    Messages: MessagesSelect<false> | MessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    LandingPage: LandingPage;
    MeasurementPage: MeasurementPage;
    InspectionPage: InspectionPage;
    ImagePage: ImagePage;
    AgriculturePage: AgriculturePage;
    OfficePage: OfficePage;
  };
  globalsSelect: {
    LandingPage: LandingPageSelect<false> | LandingPageSelect<true>;
    MeasurementPage: MeasurementPageSelect<false> | MeasurementPageSelect<true>;
    InspectionPage: InspectionPageSelect<false> | InspectionPageSelect<true>;
    ImagePage: ImagePageSelect<false> | ImagePageSelect<true>;
    AgriculturePage: AgriculturePageSelect<false> | AgriculturePageSelect<true>;
    OfficePage: OfficePageSelect<false> | OfficePageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'Users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Resources".
 */
export interface Resource {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Messages".
 */
export interface Message {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'Users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'Resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'Messages';
        value: string | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'Users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'Users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LandingPage".
 */
export interface LandingPage {
  id: string;
  cta?: {
    image?: (string | null) | Resource;
    imageMobile?: (string | null) | Resource;
    heading?: string | null;
    text?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    servicesButton?: {
      text?: string | null;
      icon?: string | null;
    };
  };
  statistics?: {
    statistic1?: {
      value?: string | null;
      title?: string | null;
      text?: string | null;
    };
    statistic2?: {
      value?: string | null;
      title?: string | null;
      text?: string | null;
    };
    statistic3?: {
      value?: string | null;
      title?: string | null;
      text?: string | null;
    };
    statistic4?: {
      value?: string | null;
      title?: string | null;
      text?: string | null;
    };
  };
  services?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    service1?: {
      image?: (string | null) | Resource;
      name?: string | null;
      text?: string | null;
      icon?: string | null;
      services?:
        | {
            name?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    service2?: {
      image?: (string | null) | Resource;
      name?: string | null;
      text?: string | null;
      icon?: string | null;
      services?:
        | {
            name?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    service3?: {
      image?: (string | null) | Resource;
      name?: string | null;
      text?: string | null;
      icon?: string | null;
      services?:
        | {
            name?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    service4?: {
      image?: (string | null) | Resource;
      name?: string | null;
      text?: string | null;
      icon?: string | null;
      services?:
        | {
            name?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    service5?: {
      image?: (string | null) | Resource;
      name?: string | null;
      text?: string | null;
      icon?: string | null;
      services?:
        | {
            name?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  about?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    benefits?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    data?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    previewImage?: (string | null) | Resource;
    previewImageLink?: string | null;
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    step1?: {
      icon?: string | null;
      title?: string | null;
      text?: string | null;
    };
    step2?: {
      icon?: string | null;
      title?: string | null;
      text?: string | null;
    };
    step3?: {
      icon?: string | null;
      title?: string | null;
      text?: string | null;
    };
    step4?: {
      icon?: string | null;
      title?: string | null;
      text?: string | null;
    };
  };
  testimonials?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    testimonial1?: {
      author?: string | null;
      position?: string | null;
      text?: string | null;
      stars?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
    };
    testimonial2?: {
      author?: string | null;
      position?: string | null;
      text?: string | null;
      stars?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
    };
    testimonial3?: {
      author?: string | null;
      position?: string | null;
      text?: string | null;
      stars?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
    };
  };
  faq?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    faqs?:
      | {
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    phone?: string | null;
    mail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MeasurementPage".
 */
export interface MeasurementPage {
  id: string;
  cta?: {
    image?: (string | null) | Resource;
    imageMobile?: (string | null) | Resource;
    name?: string | null;
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
  };
  richtext?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  gallery?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    images?:
      | {
          image?: (string | null) | Resource;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  details?: {
    title?: string | null;
    subtitle?: string | null;
    details?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  information?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    details?:
      | {
          name?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    block?: {
      title?: string | null;
      subtitle?: string | null;
      list?:
        | {
            text?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  benefits?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    benefits?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    phone?: string | null;
    mail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InspectionPage".
 */
export interface InspectionPage {
  id: string;
  cta?: {
    image?: (string | null) | Resource;
    imageMobile?: (string | null) | Resource;
    name?: string | null;
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
  };
  information?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    blocks?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  gallery?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    images?:
      | {
          image?: (string | null) | Resource;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  details?: {
    title?: string | null;
    subtitle?: string | null;
    details?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  usages?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    usages?:
      | {
          title?: string | null;
          list?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  benefits?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    benefits?:
      | {
          benefit?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    phone?: string | null;
    mail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImagePage".
 */
export interface ImagePage {
  id: string;
  cta?: {
    image?: (string | null) | Resource;
    imageMobile?: (string | null) | Resource;
    name?: string | null;
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
  };
  richtext?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  gallery?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    thumbnail?: (string | null) | Resource;
    link?: string | null;
    images?:
      | {
          image?: (string | null) | Resource;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  details?: {
    title?: string | null;
    subtitle?: string | null;
    details?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          linkAvailable?: boolean | null;
          link?: string | null;
          linkText?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  equipment?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    blocks?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    heading?: string | null;
    information?:
      | {
          name?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  usages?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    benefits?:
      | {
          benefit?: string | null;
          id?: string | null;
        }[]
      | null;
    blocks?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    phone?: string | null;
    mail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgriculturePage".
 */
export interface AgriculturePage {
  id: string;
  cta?: {
    image?: (string | null) | Resource;
    imageMobile?: (string | null) | Resource;
    name?: string | null;
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
  };
  information?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    details?:
      | {
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
    block?: {
      icon?: string | null;
      title?: string | null;
      subtitle?: string | null;
      statistic1?: {
        name?: string | null;
        value?: string | null;
      };
      statistic2?: {
        name?: string | null;
        value?: string | null;
      };
      statistic3?: {
        name?: string | null;
        value?: string | null;
      };
      statistic4?: {
        name?: string | null;
        value?: string | null;
      };
    };
  };
  gallery?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    images?:
      | {
          image?: (string | null) | Resource;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  details?: {
    title?: string | null;
    subtitle?: string | null;
    details?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  richtext?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    blocks?:
      | {
          value?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  benefits?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    benefits?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    phone?: string | null;
    mail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfficePage".
 */
export interface OfficePage {
  id: string;
  cta?: {
    image?: (string | null) | Resource;
    imageMobile?: (string | null) | Resource;
    name?: string | null;
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
  };
  richtext?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  gallery?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    images?:
      | {
          image?: (string | null) | Resource;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  details?: {
    title?: string | null;
    subtitle?: string | null;
    details?:
      | {
          icon?: string | null;
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  information?: {
    title?: string | null;
    subtitle?: string | null;
    texts?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    details?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    block?: {
      icon?: string | null;
      title?: string | null;
      subtitle?: string | null;
      list?:
        | {
            text?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  benefits?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    benefits?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    title?: string | null;
    subtitle?: string | null;
    appointmentButton?: {
      text?: string | null;
      icon?: string | null;
    };
    phone?: string | null;
    mail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LandingPage_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        image?: T;
        imageMobile?: T;
        heading?: T;
        text?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        servicesButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
      };
  statistics?:
    | T
    | {
        statistic1?:
          | T
          | {
              value?: T;
              title?: T;
              text?: T;
            };
        statistic2?:
          | T
          | {
              value?: T;
              title?: T;
              text?: T;
            };
        statistic3?:
          | T
          | {
              value?: T;
              title?: T;
              text?: T;
            };
        statistic4?:
          | T
          | {
              value?: T;
              title?: T;
              text?: T;
            };
      };
  services?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        service1?:
          | T
          | {
              image?: T;
              name?: T;
              text?: T;
              icon?: T;
              services?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
            };
        service2?:
          | T
          | {
              image?: T;
              name?: T;
              text?: T;
              icon?: T;
              services?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
            };
        service3?:
          | T
          | {
              image?: T;
              name?: T;
              text?: T;
              icon?: T;
              services?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
            };
        service4?:
          | T
          | {
              image?: T;
              name?: T;
              text?: T;
              icon?: T;
              services?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
            };
        service5?:
          | T
          | {
              image?: T;
              name?: T;
              text?: T;
              icon?: T;
              services?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
            };
      };
  about?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        data?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        previewImage?: T;
        previewImageLink?: T;
        title?: T;
        subtitle?: T;
        text?: T;
        step1?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
            };
        step2?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
            };
        step3?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
            };
        step4?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
            };
      };
  testimonials?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        testimonial1?:
          | T
          | {
              author?: T;
              position?: T;
              text?: T;
              stars?: T;
            };
        testimonial2?:
          | T
          | {
              author?: T;
              position?: T;
              text?: T;
              stars?: T;
            };
        testimonial3?:
          | T
          | {
              author?: T;
              position?: T;
              text?: T;
              stars?: T;
            };
      };
  faq?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        phone?: T;
        mail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MeasurementPage_select".
 */
export interface MeasurementPageSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        image?: T;
        imageMobile?: T;
        name?: T;
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
      };
  richtext?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        images?:
          | T
          | {
              image?: T;
              description?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        title?: T;
        subtitle?: T;
        details?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  information?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        details?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
        block?:
          | T
          | {
              title?: T;
              subtitle?: T;
              list?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        phone?: T;
        mail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InspectionPage_select".
 */
export interface InspectionPageSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        image?: T;
        imageMobile?: T;
        name?: T;
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
      };
  information?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        blocks?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        images?:
          | T
          | {
              image?: T;
              description?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        title?: T;
        subtitle?: T;
        details?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  usages?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        usages?:
          | T
          | {
              title?: T;
              list?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        benefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        phone?: T;
        mail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImagePage_select".
 */
export interface ImagePageSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        image?: T;
        imageMobile?: T;
        name?: T;
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
      };
  richtext?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        thumbnail?: T;
        link?: T;
        images?:
          | T
          | {
              image?: T;
              description?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        title?: T;
        subtitle?: T;
        details?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              linkAvailable?: T;
              link?: T;
              linkText?: T;
              id?: T;
            };
      };
  equipment?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        blocks?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
        heading?: T;
        information?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
      };
  usages?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        benefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
        blocks?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        phone?: T;
        mail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgriculturePage_select".
 */
export interface AgriculturePageSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        image?: T;
        imageMobile?: T;
        name?: T;
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
      };
  information?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        details?:
          | T
          | {
              detail?: T;
              id?: T;
            };
        block?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              statistic1?:
                | T
                | {
                    name?: T;
                    value?: T;
                  };
              statistic2?:
                | T
                | {
                    name?: T;
                    value?: T;
                  };
              statistic3?:
                | T
                | {
                    name?: T;
                    value?: T;
                  };
              statistic4?:
                | T
                | {
                    name?: T;
                    value?: T;
                  };
            };
      };
  gallery?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        images?:
          | T
          | {
              image?: T;
              description?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        title?: T;
        subtitle?: T;
        details?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  richtext?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        blocks?:
          | T
          | {
              value?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        phone?: T;
        mail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfficePage_select".
 */
export interface OfficePageSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        image?: T;
        imageMobile?: T;
        name?: T;
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
      };
  richtext?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        images?:
          | T
          | {
              image?: T;
              description?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        title?: T;
        subtitle?: T;
        details?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  information?:
    | T
    | {
        title?: T;
        subtitle?: T;
        texts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        details?:
          | T
          | {
              name?: T;
              id?: T;
            };
        block?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              list?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        title?: T;
        subtitle?: T;
        appointmentButton?:
          | T
          | {
              text?: T;
              icon?: T;
            };
        phone?: T;
        mail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}