/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres"
import {
    pgTable,
    index,
    uniqueIndex,
    foreignKey,
    integer,
    uuid,
    varchar,
    timestamp,
    numeric,
    jsonb,
    serial
} from "@payloadcms/db-postgres/drizzle/pg-core"
import { sql, relations } from "@payloadcms/db-postgres/drizzle"

export const users_sessions = pgTable(
    "users_sessions",
    {
        _order: integer("_order").notNull(),
        _parentID: uuid("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
        expiresAt: timestamp("expires_at", { mode: "string", withTimezone: true, precision: 3 }).notNull()
    },
    (columns) => [
        index("users_sessions_order_idx").on(columns._order),
        index("users_sessions_parent_id_idx").on(columns._parentID),
        foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [users.id],
            name: "users_sessions_parent_id_fk"
        }).onDelete("cascade")
    ]
)

export const users = pgTable(
    "users",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        firstName: varchar("first_name"),
        lastName: varchar("last_name"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        email: varchar("email").notNull(),
        resetPasswordToken: varchar("reset_password_token"),
        resetPasswordExpiration: timestamp("reset_password_expiration", {
            mode: "string",
            withTimezone: true,
            precision: 3
        }),
        salt: varchar("salt"),
        hash: varchar("hash"),
        loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
        lockUntil: timestamp("lock_until", { mode: "string", withTimezone: true, precision: 3 })
    },
    (columns) => [
        index("users_updated_at_idx").on(columns.updatedAt),
        index("users_created_at_idx").on(columns.createdAt),
        uniqueIndex("users_email_idx").on(columns.email)
    ]
)

export const resources = pgTable(
    "resources",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        alt: varchar("alt"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        url: varchar("url"),
        thumbnailURL: varchar("thumbnail_u_r_l"),
        filename: varchar("filename"),
        mimeType: varchar("mime_type"),
        filesize: numeric("filesize", { mode: "number" }),
        width: numeric("width", { mode: "number" }),
        height: numeric("height", { mode: "number" }),
        focalX: numeric("focal_x", { mode: "number" }),
        focalY: numeric("focal_y", { mode: "number" })
    },
    (columns) => [
        index("resources_updated_at_idx").on(columns.updatedAt),
        index("resources_created_at_idx").on(columns.createdAt),
        uniqueIndex("resources_filename_idx").on(columns.filename)
    ]
)

export const payload_kv = pgTable(
    "payload_kv",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        key: varchar("key").notNull(),
        data: jsonb("data").notNull()
    },
    (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)]
)

export const payload_locked_documents = pgTable(
    "payload_locked_documents",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        globalSlug: varchar("global_slug"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull()
    },
    (columns) => [
        index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
        index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
        index("payload_locked_documents_created_at_idx").on(columns.createdAt)
    ]
)

export const payload_locked_documents_rels = pgTable(
    "payload_locked_documents_rels",
    {
        id: serial("id").primaryKey(),
        order: integer("order"),
        parent: uuid("parent_id").notNull(),
        path: varchar("path").notNull(),
        UsersID: uuid("users_id"),
        ResourcesID: uuid("resources_id")
    },
    (columns) => [
        index("payload_locked_documents_rels_order_idx").on(columns.order),
        index("payload_locked_documents_rels_parent_idx").on(columns.parent),
        index("payload_locked_documents_rels_path_idx").on(columns.path),
        index("payload_locked_documents_rels_users_id_idx").on(columns.UsersID),
        index("payload_locked_documents_rels_resources_id_idx").on(columns.ResourcesID),
        foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [payload_locked_documents.id],
            name: "payload_locked_documents_rels_parent_fk"
        }).onDelete("cascade"),
        foreignKey({
            columns: [columns["UsersID"]],
            foreignColumns: [users.id],
            name: "payload_locked_documents_rels_users_fk"
        }).onDelete("cascade"),
        foreignKey({
            columns: [columns["ResourcesID"]],
            foreignColumns: [resources.id],
            name: "payload_locked_documents_rels_resources_fk"
        }).onDelete("cascade")
    ]
)

export const payload_preferences = pgTable(
    "payload_preferences",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        key: varchar("key"),
        value: jsonb("value"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull()
    },
    (columns) => [
        index("payload_preferences_key_idx").on(columns.key),
        index("payload_preferences_updated_at_idx").on(columns.updatedAt),
        index("payload_preferences_created_at_idx").on(columns.createdAt)
    ]
)

export const payload_preferences_rels = pgTable(
    "payload_preferences_rels",
    {
        id: serial("id").primaryKey(),
        order: integer("order"),
        parent: uuid("parent_id").notNull(),
        path: varchar("path").notNull(),
        UsersID: uuid("users_id")
    },
    (columns) => [
        index("payload_preferences_rels_order_idx").on(columns.order),
        index("payload_preferences_rels_parent_idx").on(columns.parent),
        index("payload_preferences_rels_path_idx").on(columns.path),
        index("payload_preferences_rels_users_id_idx").on(columns.UsersID),
        foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [payload_preferences.id],
            name: "payload_preferences_rels_parent_fk"
        }).onDelete("cascade"),
        foreignKey({
            columns: [columns["UsersID"]],
            foreignColumns: [users.id],
            name: "payload_preferences_rels_users_fk"
        }).onDelete("cascade")
    ]
)

export const payload_migrations = pgTable(
    "payload_migrations",
    {
        id: uuid("id").defaultRandom().primaryKey(),
        name: varchar("name"),
        batch: numeric("batch", { mode: "number" }),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull()
    },
    (columns) => [
        index("payload_migrations_updated_at_idx").on(columns.updatedAt),
        index("payload_migrations_created_at_idx").on(columns.createdAt)
    ]
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
    _parentID: one(users, {
        fields: [users_sessions._parentID],
        references: [users.id],
        relationName: "sessions"
    })
}))
export const relations_users = relations(users, ({ many }) => ({
    sessions: many(users_sessions, {
        relationName: "sessions"
    })
}))
export const relations_resources = relations(resources, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
    parent: one(payload_locked_documents, {
        fields: [payload_locked_documents_rels.parent],
        references: [payload_locked_documents.id],
        relationName: "_rels"
    }),
    UsersID: one(users, {
        fields: [payload_locked_documents_rels.UsersID],
        references: [users.id],
        relationName: "Users"
    }),
    ResourcesID: one(resources, {
        fields: [payload_locked_documents_rels.ResourcesID],
        references: [resources.id],
        relationName: "Resources"
    })
}))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
        relationName: "_rels"
    })
}))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
    parent: one(payload_preferences, {
        fields: [payload_preferences_rels.parent],
        references: [payload_preferences.id],
        relationName: "_rels"
    }),
    UsersID: one(users, {
        fields: [payload_preferences_rels.UsersID],
        references: [users.id],
        relationName: "Users"
    })
}))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
    _rels: many(payload_preferences_rels, {
        relationName: "_rels"
    })
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
    users_sessions: typeof users_sessions
    users: typeof users
    resources: typeof resources
    payload_kv: typeof payload_kv
    payload_locked_documents: typeof payload_locked_documents
    payload_locked_documents_rels: typeof payload_locked_documents_rels
    payload_preferences: typeof payload_preferences
    payload_preferences_rels: typeof payload_preferences_rels
    payload_migrations: typeof payload_migrations
    relations_users_sessions: typeof relations_users_sessions
    relations_users: typeof relations_users
    relations_resources: typeof relations_resources
    relations_payload_kv: typeof relations_payload_kv
    relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
    relations_payload_locked_documents: typeof relations_payload_locked_documents
    relations_payload_preferences_rels: typeof relations_payload_preferences_rels
    relations_payload_preferences: typeof relations_payload_preferences
    relations_payload_migrations: typeof relations_payload_migrations
}

declare module "@payloadcms/db-postgres" {
    export interface GeneratedDatabaseSchema {
        schema: DatabaseSchema
    }
}
